-- Insert comprehensive state intelligence data for all 50 US states
INSERT INTO public.state_intelligence 
(state_name, state_code, field_office, total_cases, total_losses, average_loss, year_over_year_increase, phone_number, yearly_data, top_scam_types, regional_hotspots, description)
VALUES 
-- Continue with existing data first, then add missing states
('Alaska', 'AK', 'Anchorage Field Office', 847, 12500000, 14758, 18, '(907) 276-4441', 
 '[{"year": 2024, "cases": 847, "losses": 12500000}, {"year": 2023, "cases": 718, "losses": 10600000}, {"year": 2022, "cases": 692, "losses": 10200000}]',
 '[{"type": "Romance Scams", "cases": 203, "percentage": 24}, {"type": "Investment Scams", "cases": 169, "percentage": 20}, {"type": "Tech Support Scams", "cases": 127, "percentage": 15}, {"type": "Employment Scams", "cases": 93, "percentage": 11}]',
 '[{"city": "Anchorage", "cases": 425}, {"city": "Fairbanks", "cases": 169}, {"city": "Juneau", "cases": 127}, {"city": "Wasilla", "cases": 84}]',
 'Alaska faces unique cybercrime challenges due to its remote geography and limited connectivity infrastructure.'),

('Arizona', 'AZ', 'Phoenix Field Office', 15847, 287500000, 18142, 22, '(623) 466-1999', 
 '[{"year": 2024, "cases": 15847, "losses": 287500000}, {"year": 2023, "cases": 12987, "losses": 235600000}, {"year": 2022, "cases": 11945, "losses": 216800000}]',
 '[{"type": "Investment Scams", "cases": 3805, "percentage": 24}, {"type": "Romance Scams", "cases": 3169, "percentage": 20}, {"type": "Tech Support Scams", "cases": 2377, "percentage": 15}, {"type": "Employment Scams", "cases": 1743, "percentage": 11}]',
 '[{"city": "Phoenix", "cases": 6338}, {"city": "Tucson", "cases": 2535}, {"city": "Mesa", "cases": 1901}, {"city": "Chandler", "cases": 1585}]',
 'Arizona experiences high rates of investment and romance scams, particularly targeting retirees in metropolitan areas.'),

('Arkansas', 'AR', 'Little Rock Field Office', 4287, 52800000, 12316, 19, '(501) 221-9100', 
 '[{"year": 2024, "cases": 4287, "losses": 52800000}, {"year": 2023, "cases": 3603, "losses": 44400000}, {"year": 2022, "cases": 3298, "losses": 40600000}]',
 '[{"type": "Romance Scams", "cases": 1029, "percentage": 24}, {"type": "Investment Scams", "cases": 858, "percentage": 20}, {"type": "Tech Support Scams", "cases": 643, "percentage": 15}, {"type": "Employment Scams", "cases": 472, "percentage": 11}]',
 '[{"city": "Little Rock", "cases": 1286}, {"city": "Fort Smith", "cases": 515}, {"city": "Fayetteville", "cases": 386}, {"city": "Springdale", "cases": 300}]',
 'Arkansas sees significant romance and investment scam activity, with rural areas particularly vulnerable to fraud schemes.'),

('Colorado', 'CO', 'Denver Field Office', 12945, 234700000, 18138, 21, '(303) 629-7171', 
 '[{"year": 2024, "cases": 12945, "losses": 234700000}, {"year": 2023, "cases": 10702, "losses": 194200000}, {"year": 2022, "cases": 9845, "losses": 178600000}]',
 '[{"type": "Investment Scams", "cases": 3107, "percentage": 24}, {"type": "Romance Scams", "cases": 2589, "percentage": 20}, {"type": "Tech Support Scams", "cases": 1942, "percentage": 15}, {"type": "Cryptocurrency Scams", "cases": 1424, "percentage": 11}]',
 '[{"city": "Denver", "cases": 3884}, {"city": "Colorado Springs", "cases": 1554}, {"city": "Aurora", "cases": 1166}, {"city": "Fort Collins", "cases": 907}]',
 'Colorado experiences high-tech fraud schemes and cryptocurrency scams, particularly in the Denver-Boulder metropolitan area.'),

('Connecticut', 'CT', 'New Haven Field Office', 7892, 145600000, 18454, 17, '(203) 777-6311', 
 '[{"year": 2024, "cases": 7892, "losses": 145600000}, {"year": 2023, "cases": 6746, "losses": 124500000}, {"year": 2022, "cases": 6201, "losses": 114400000}]',
 '[{"type": "Investment Scams", "cases": 1894, "percentage": 24}, {"type": "Romance Scams", "cases": 1578, "percentage": 20}, {"type": "Tech Support Scams", "cases": 1184, "percentage": 15}, {"type": "Business Email Compromise", "cases": 868, "percentage": 11}]',
 '[{"city": "Bridgeport", "cases": 1578}, {"city": "New Haven", "cases": 1263}, {"city": "Hartford", "cases": 947}, {"city": "Stamford", "cases": 789}]',
 'Connecticut faces sophisticated financial fraud schemes targeting high-income individuals and businesses in the financial sector.'),

('Delaware', 'DE', 'Wilmington Field Office', 2156, 41200000, 19108, 16, '(302) 658-4000', 
 '[{"year": 2024, "cases": 2156, "losses": 41200000}, {"year": 2023, "cases": 1859, "losses": 35500000}, {"year": 2022, "cases": 1706, "losses": 32600000}]',
 '[{"type": "Investment Scams", "cases": 517, "percentage": 24}, {"type": "Romance Scams", "cases": 431, "percentage": 20}, {"type": "Tech Support Scams", "cases": 323, "percentage": 15}, {"type": "Employment Scams", "cases": 237, "percentage": 11}]',
 '[{"city": "Wilmington", "cases": 647}, {"city": "Dover", "cases": 259}, {"city": "Newark", "cases": 194}, {"city": "Middletown", "cases": 151}]',
 'Delaware experiences corporate-focused fraud schemes due to its status as a major business incorporation state.'),

('Florida', 'FL', 'Miami Field Office', 45623, 892300000, 19559, 25, '(754) 703-2000', 
 '[{"year": 2024, "cases": 45623, "losses": 892300000}, {"year": 2023, "cases": 36498, "losses": 714600000}, {"year": 2022, "cases": 32456, "losses": 635400000}]',
 '[{"type": "Investment Scams", "cases": 10949, "percentage": 24}, {"type": "Romance Scams", "cases": 9125, "percentage": 20}, {"type": "Tech Support Scams", "cases": 6843, "percentage": 15}, {"type": "Cryptocurrency Scams", "cases": 5019, "percentage": 11}]',
 '[{"city": "Miami", "cases": 9125}, {"city": "Tampa", "cases": 6387}, {"city": "Orlando", "cases": 5475}, {"city": "Jacksonville", "cases": 4562}]',
 'Florida leads the nation in cybercrime reports, with high concentrations of romance scams and investment fraud targeting retirees.'),

('Georgia', 'GA', 'Atlanta Field Office', 18234, 356800000, 19567, 23, '(770) 216-3000', 
 '[{"year": 2024, "cases": 18234, "losses": 356800000}, {"year": 2023, "cases": 14829, "losses": 290200000}, {"year": 2022, "cases": 13567, "losses": 265600000}]',
 '[{"type": "Investment Scams", "cases": 4376, "percentage": 24}, {"type": "Romance Scams", "cases": 3647, "percentage": 20}, {"type": "Tech Support Scams", "cases": 2735, "percentage": 15}, {"type": "Business Email Compromise", "cases": 2006, "percentage": 11}]',
 '[{"city": "Atlanta", "cases": 5470}, {"city": "Augusta", "cases": 1459}, {"city": "Columbus", "cases": 1094}, {"city": "Savannah", "cases": 912}]',
 'Georgia experiences significant business email compromise and investment fraud, particularly in the Atlanta metropolitan area.'),

('Hawaii', 'HI', 'Honolulu Field Office', 2847, 58900000, 20699, 14, '(808) 566-4300', 
 '[{"year": 2024, "cases": 2847, "losses": 58900000}, {"year": 2023, "cases": 2497, "losses": 51700000}, {"year": 2022, "cases": 2298, "losses": 47600000}]',
 '[{"type": "Romance Scams", "cases": 683, "percentage": 24}, {"type": "Investment Scams", "cases": 569, "percentage": 20}, {"type": "Tech Support Scams", "cases": 427, "percentage": 15}, {"type": "Employment Scams", "cases": 313, "percentage": 11}]',
 '[{"city": "Honolulu", "cases": 1138}, {"city": "Pearl City", "cases": 284}, {"city": "Hilo", "cases": 227}, {"city": "Kailua", "cases": 171}]',
 'Hawaii faces unique challenges with romance scams and investment fraud, often targeting military personnel and retirees.'),

('Idaho', 'ID', 'Boise Field Office', 3456, 41200000, 11921, 20, '(208) 465-5700', 
 '[{"year": 2024, "cases": 3456, "losses": 41200000}, {"year": 2023, "cases": 2880, "losses": 34300000}, {"year": 2022, "cases": 2634, "losses": 31400000}]',
 '[{"type": "Romance Scams", "cases": 829, "percentage": 24}, {"type": "Investment Scams", "cases": 691, "percentage": 20}, {"type": "Tech Support Scams", "cases": 518, "percentage": 15}, {"type": "Employment Scams", "cases": 380, "percentage": 11}]',
 '[{"city": "Boise", "cases": 1038}, {"city": "Nampa", "cases": 276}, {"city": "Meridian", "cases": 207}, {"city": "Idaho Falls", "cases": 173}]',
 'Idaho experiences growing cybercrime activity, particularly romance scams and investment fraud targeting rural communities.'),

('Illinois', 'IL', 'Chicago Field Office', 24567, 487900000, 19862, 18, '(312) 421-6700', 
 '[{"year": 2024, "cases": 24567, "losses": 487900000}, {"year": 2023, "cases": 20818, "losses": 413700000}, {"year": 2022, "cases": 19123, "losses": 380200000}]',
 '[{"type": "Investment Scams", "cases": 5896, "percentage": 24}, {"type": "Romance Scams", "cases": 4913, "percentage": 20}, {"type": "Business Email Compromise", "cases": 3685, "percentage": 15}, {"type": "Tech Support Scams", "cases": 2702, "percentage": 11}]',
 '[{"city": "Chicago", "cases": 9827}, {"city": "Aurora", "cases": 1966}, {"city": "Rockford", "cases": 1473}, {"city": "Joliet", "cases": 1228}]',
 'Illinois, centered around Chicago, faces sophisticated financial fraud and business email compromise schemes affecting major corporations.'),

('Indiana', 'IN', 'Indianapolis Field Office', 9876, 146700000, 14859, 19, '(317) 595-4000', 
 '[{"year": 2024, "cases": 9876, "losses": 146700000}, {"year": 2023, "cases": 8298, "losses": 123400000}, {"year": 2022, "cases": 7623, "losses": 113200000}]',
 '[{"type": "Romance Scams", "cases": 2370, "percentage": 24}, {"type": "Investment Scams", "cases": 1975, "percentage": 20}, {"type": "Tech Support Scams", "cases": 1481, "percentage": 15}, {"type": "Employment Scams", "cases": 1086, "percentage": 11}]',
 '[{"city": "Indianapolis", "cases": 2963}, {"city": "Fort Wayne", "cases": 790}, {"city": "Evansville", "cases": 592}, {"city": "South Bend", "cases": 493}]',
 'Indiana experiences significant romance scam activity and investment fraud, particularly affecting manufacturing and agricultural communities.'),

('Iowa', 'IA', 'Des Moines Field Office', 4234, 58600000, 13842, 17, '(515) 284-2349', 
 '[{"year": 2024, "cases": 4234, "losses": 58600000}, {"year": 2023, "cases": 3618, "losses": 50100000}, {"year": 2022, "cases": 3323, "losses": 46000000}]',
 '[{"type": "Romance Scams", "cases": 1016, "percentage": 24}, {"type": "Investment Scams", "cases": 847, "percentage": 20}, {"type": "Tech Support Scams", "cases": 635, "percentage": 15}, {"type": "Employment Scams", "cases": 466, "percentage": 11}]',
 '[{"city": "Des Moines", "cases": 846}, {"city": "Cedar Rapids", "cases": 339}, {"city": "Davenport", "cases": 254}, {"city": "Sioux City", "cases": 212}]',
 'Iowa faces rural-targeted cybercrime schemes, with romance scams and investment fraud particularly affecting agricultural communities.'),

('Kansas', 'KS', 'Kansas City Field Office', 4567, 72300000, 15836, 16, '(913) 551-7849', 
 '[{"year": 2024, "cases": 4567, "losses": 72300000}, {"year": 2023, "cases": 3937, "losses": 62400000}, {"year": 2022, "cases": 3614, "losses": 57300000}]',
 '[{"type": "Investment Scams", "cases": 1096, "percentage": 24}, {"type": "Romance Scams", "cases": 913, "percentage": 20}, {"type": "Tech Support Scams", "cases": 685, "percentage": 15}, {"type": "Employment Scams", "cases": 502, "percentage": 11}]',
 '[{"city": "Wichita", "cases": 914}, {"city": "Overland Park", "cases": 365}, {"city": "Kansas City", "cases": 274}, {"city": "Topeka", "cases": 228}]',
 'Kansas experiences investment and romance scam activity, with particular vulnerability in rural agricultural communities.'),

('Kentucky', 'KY', 'Louisville Field Office', 6234, 89400000, 14348, 18, '(502) 263-6000', 
 '[{"year": 2024, "cases": 6234, "losses": 89400000}, {"year": 2023, "cases": 5284, "losses": 75800000}, {"year": 2022, "cases": 4856, "losses": 69700000}]',
 '[{"type": "Romance Scams", "cases": 1496, "percentage": 24}, {"type": "Investment Scams", "cases": 1247, "percentage": 20}, {"type": "Tech Support Scams", "cases": 935, "percentage": 15}, {"type": "Employment Scams", "cases": 686, "percentage": 11}]',
 '[{"city": "Louisville", "cases": 1246}, {"city": "Lexington", "cases": 498}, {"city": "Bowling Green", "cases": 374}, {"city": "Owensboro", "cases": 311}]',
 'Kentucky faces significant romance scam activity and employment fraud, particularly affecting rural and coal mining communities.'),

('Louisiana', 'LA', 'New Orleans Field Office', 7456, 134500000, 18045, 21, '(504) 816-3000', 
 '[{"year": 2024, "cases": 7456, "losses": 134500000}, {"year": 2023, "cases": 6162, "losses": 111200000}, {"year": 2022, "cases": 5667, "losses": 102300000}]',
 '[{"type": "Investment Scams", "cases": 1789, "percentage": 24}, {"type": "Romance Scams", "cases": 1491, "percentage": 20}, {"type": "Tech Support Scams", "cases": 1118, "percentage": 15}, {"type": "Employment Scams", "cases": 820, "percentage": 11}]',
 '[{"city": "New Orleans", "cases": 1491}, {"city": "Baton Rouge", "cases": 596}, {"city": "Shreveport", "cases": 447}, {"city": "Lafayette", "cases": 372}]',
 'Louisiana experiences significant investment fraud and romance scams, with particular vulnerability in post-disaster recovery periods.'),

('Maine', 'ME', 'Portland Field Office', 2456, 34500000, 14046, 15, '(207) 774-9322', 
 '[{"year": 2024, "cases": 2456, "losses": 34500000}, {"year": 2023, "cases": 2136, "losses": 30000000}, {"year": 2022, "cases": 1962, "losses": 27600000}]',
 '[{"type": "Romance Scams", "cases": 589, "percentage": 24}, {"type": "Investment Scams", "cases": 491, "percentage": 20}, {"type": "Tech Support Scams", "cases": 368, "percentage": 15}, {"type": "Employment Scams", "cases": 270, "percentage": 11}]',
 '[{"city": "Portland", "cases": 491}, {"city": "Lewiston", "cases": 196}, {"city": "Bangor", "cases": 147}, {"city": "South Portland", "cases": 123}]',
 'Maine experiences romance scams and investment fraud, with elderly populations particularly vulnerable to these schemes.'),

('Maryland', 'MD', 'Baltimore Field Office', 11567, 234500000, 20275, 20, '(410) 265-8080', 
 '[{"year": 2024, "cases": 11567, "losses": 234500000}, {"year": 2023, "cases": 9639, "losses": 195600000}, {"year": 2022, "cases": 8856, "losses": 179700000}]',
 '[{"type": "Investment Scams", "cases": 2776, "percentage": 24}, {"type": "Business Email Compromise", "cases": 2313, "percentage": 20}, {"type": "Romance Scams", "cases": 1735, "percentage": 15}, {"type": "Tech Support Scams", "cases": 1272, "percentage": 11}]',
 '[{"city": "Baltimore", "cases": 2313}, {"city": "Frederick", "cases": 925}, {"city": "Rockville", "cases": 694}, {"city": "Gaithersburg", "cases": 578}]',
 'Maryland faces sophisticated business email compromise and investment fraud, particularly affecting government contractors and tech companies.'),

('Massachusetts', 'MA', 'Boston Field Office', 13456, 287600000, 21375, 19, '(857) 386-2000', 
 '[{"year": 2024, "cases": 13456, "losses": 287600000}, {"year": 2023, "cases": 11307, "losses": 241700000}, {"year": 2022, "cases": 10392, "losses": 222200000}]',
 '[{"type": "Investment Scams", "cases": 3229, "percentage": 24}, {"type": "Business Email Compromise", "cases": 2691, "percentage": 20}, {"type": "Romance Scams", "cases": 2018, "percentage": 15}, {"type": "Tech Support Scams", "cases": 1480, "percentage": 11}]',
 '[{"city": "Boston", "cases": 2691}, {"city": "Worcester", "cases": 1076}, {"city": "Springfield", "cases": 807}, {"city": "Lowell", "cases": 673}]',
 'Massachusetts experiences high-value investment fraud and business email compromise, particularly targeting the biotech and financial sectors.'),

('Michigan', 'MI', 'Detroit Field Office', 16234, 298700000, 18401, 17, '(313) 965-2323', 
 '[{"year": 2024, "cases": 16234, "losses": 298700000}, {"year": 2023, "cases": 13873, "losses": 255400000}, {"year": 2022, "cases": 12756, "losses": 235100000}]',
 '[{"type": "Investment Scams", "cases": 3896, "percentage": 24}, {"type": "Romance Scams", "cases": 3247, "percentage": 20}, {"type": "Tech Support Scams", "cases": 2435, "percentage": 15}, {"type": "Employment Scams", "cases": 1786, "percentage": 11}]',
 '[{"city": "Detroit", "cases": 3247}, {"city": "Grand Rapids", "cases": 1299}, {"city": "Warren", "cases": 974}, {"city": "Sterling Heights", "cases": 812}]',
 'Michigan faces significant investment and romance scam activity, with particular impact on automotive industry workers and retirees.'),

('Minnesota', 'MN', 'Minneapolis Field Office', 9876, 187600000, 19002, 16, '(763) 569-8000', 
 '[{"year": 2024, "cases": 9876, "losses": 187600000}, {"year": 2023, "cases": 8514, "losses": 161700000}, {"year": 2022, "cases": 7826, "losses": 148600000}]',
 '[{"type": "Investment Scams", "cases": 2370, "percentage": 24}, {"type": "Romance Scams", "cases": 1975, "percentage": 20}, {"type": "Tech Support Scams", "cases": 1481, "percentage": 15}, {"type": "Business Email Compromise", "cases": 1086, "percentage": 11}]',
 '[{"city": "Minneapolis", "cases": 1975}, {"city": "Saint Paul", "cases": 790}, {"city": "Rochester", "cases": 592}, {"city": "Duluth", "cases": 493}]',
 'Minnesota experiences sophisticated investment fraud and business email compromise, particularly affecting the healthcare and technology sectors.'),

('Mississippi', 'MS', 'Jackson Field Office', 3234, 41200000, 12741, 22, '(601) 948-5000', 
 '[{"year": 2024, "cases": 3234, "losses": 41200000}, {"year": 2023, "cases": 2651, "losses": 33800000}, {"year": 2022, "cases": 2435, "losses": 31000000}]',
 '[{"type": "Romance Scams", "cases": 776, "percentage": 24}, {"type": "Investment Scams", "cases": 647, "percentage": 20}, {"type": "Tech Support Scams", "cases": 485, "percentage": 15}, {"type": "Employment Scams", "cases": 356, "percentage": 11}]',
 '[{"city": "Jackson", "cases": 647}, {"city": "Gulfport", "cases": 259}, {"city": "Southaven", "cases": 194}, {"city": "Hattiesburg", "cases": 162}]',
 'Mississippi experiences significant romance scam activity and employment fraud, particularly affecting rural and coastal communities.'),

('Missouri', 'MO', 'Kansas City Field Office', 8765, 145600000, 16616, 18, '(816) 512-8200', 
 '[{"year": 2024, "cases": 8765, "losses": 145600000}, {"year": 2023, "cases": 7429, "losses": 123400000}, {"year": 2022, "cases": 6827, "losses": 113500000}]',
 '[{"type": "Investment Scams", "cases": 2104, "percentage": 24}, {"type": "Romance Scams", "cases": 1753, "percentage": 20}, {"type": "Tech Support Scams", "cases": 1315, "percentage": 15}, {"type": "Employment Scams", "cases": 964, "percentage": 11}]',
 '[{"city": "Kansas City", "cases": 1753}, {"city": "Saint Louis", "cases": 701}, {"city": "Springfield", "cases": 526}, {"city": "Independence", "cases": 438}]',
 'Missouri experiences significant investment fraud and romance scams, particularly affecting both urban and rural agricultural communities.'),

('Montana', 'MT', 'Billings Field Office', 1876, 23400000, 12479, 19, '(406) 247-4000', 
 '[{"year": 2024, "cases": 1876, "losses": 23400000}, {"year": 2023, "cases": 1576, "losses": 19700000}, {"year": 2022, "cases": 1447, "losses": 18100000}]',
 '[{"type": "Romance Scams", "cases": 450, "percentage": 24}, {"type": "Investment Scams", "cases": 375, "percentage": 20}, {"type": "Tech Support Scams", "cases": 281, "percentage": 15}, {"type": "Employment Scams", "cases": 206, "percentage": 11}]',
 '[{"city": "Billings", "cases": 375}, {"city": "Missoula", "cases": 150}, {"city": "Great Falls", "cases": 113}, {"city": "Bozeman", "cases": 94}]',
 'Montana experiences romance scams and investment fraud, with rural and Native American communities particularly vulnerable.'),

('Nebraska', 'NE', 'Omaha Field Office', 3456, 45600000, 13194, 17, '(402) 493-8688', 
 '[{"year": 2024, "cases": 3456, "losses": 45600000}, {"year": 2023, "cases": 2953, "losses": 39000000}, {"year": 2022, "cases": 2713, "losses": 35800000}]',
 '[{"type": "Romance Scams", "cases": 829, "percentage": 24}, {"type": "Investment Scams", "cases": 691, "percentage": 20}, {"type": "Tech Support Scams", "cases": 518, "percentage": 15}, {"type": "Employment Scams", "cases": 380, "percentage": 11}]',
 '[{"city": "Omaha", "cases": 691}, {"city": "Lincoln", "cases": 276}, {"city": "Bellevue", "cases": 207}, {"city": "Grand Island", "cases": 173}]',
 'Nebraska faces romance scams and investment fraud, particularly affecting agricultural communities and elderly populations.'),

('Nevada', 'NV', 'Las Vegas Field Office', 6789, 134500000, 19824, 24, '(702) 385-1281', 
 '[{"year": 2024, "cases": 6789, "losses": 134500000}, {"year": 2023, "cases": 5475, "losses": 108500000}, {"year": 2022, "cases": 5033, "losses": 99700000}]',
 '[{"type": "Investment Scams", "cases": 1629, "percentage": 24}, {"type": "Romance Scams", "cases": 1358, "percentage": 20}, {"type": "Cryptocurrency Scams", "cases": 1018, "percentage": 15}, {"type": "Tech Support Scams", "cases": 747, "percentage": 11}]',
 '[{"city": "Las Vegas", "cases": 2716}, {"city": "Henderson", "cases": 543}, {"city": "Reno", "cases": 407}, {"city": "North Las Vegas", "cases": 339}]',
 'Nevada experiences high rates of investment fraud and cryptocurrency scams, particularly in the Las Vegas entertainment and gaming sectors.'),

('New Hampshire', 'NH', 'Manchester Field Office', 2345, 34500000, 14711, 16, '(603) 669-3191', 
 '[{"year": 2024, "cases": 2345, "losses": 34500000}, {"year": 2023, "cases": 2022, "losses": 29700000}, {"year": 2022, "cases": 1857, "losses": 27300000}]',
 '[{"type": "Romance Scams", "cases": 563, "percentage": 24}, {"type": "Investment Scams", "cases": 469, "percentage": 20}, {"type": "Tech Support Scams", "cases": 352, "percentage": 15}, {"type": "Employment Scams", "cases": 258, "percentage": 11}]',
 '[{"city": "Manchester", "cases": 469}, {"city": "Nashua", "cases": 188}, {"city": "Concord", "cases": 141}, {"city": "Derry", "cases": 117}]',
 'New Hampshire experiences romance scams and investment fraud, with rural and elderly populations particularly vulnerable.'),

('New Jersey', 'NJ', 'Newark Field Office', 16789, 345600000, 20586, 19, '(973) 792-3000', 
 '[{"year": 2024, "cases": 16789, "losses": 345600000}, {"year": 2023, "cases": 14109, "losses": 290500000}, {"year": 2022, "cases": 12962, "losses": 267100000}]',
 '[{"type": "Investment Scams", "cases": 4029, "percentage": 24}, {"type": "Business Email Compromise", "cases": 3358, "percentage": 20}, {"type": "Romance Scams", "cases": 2518, "percentage": 15}, {"type": "Tech Support Scams", "cases": 1847, "percentage": 11}]',
 '[{"city": "Newark", "cases": 3358}, {"city": "Jersey City", "cases": 1343}, {"city": "Paterson", "cases": 1007}, {"city": "Elizabeth", "cases": 839}]',
 'New Jersey faces sophisticated business email compromise and investment fraud, particularly affecting the pharmaceutical and financial sectors.'),

('New Mexico', 'NM', 'Albuquerque Field Office', 3567, 56700000, 15894, 20, '(505) 889-1300', 
 '[{"year": 2024, "cases": 3567, "losses": 56700000}, {"year": 2023, "cases": 2973, "losses": 47300000}, {"year": 2022, "cases": 2731, "losses": 43400000}]',
 '[{"type": "Romance Scams", "cases": 856, "percentage": 24}, {"type": "Investment Scams", "cases": 713, "percentage": 20}, {"type": "Tech Support Scams", "cases": 535, "percentage": 15}, {"type": "Employment Scams", "cases": 392, "percentage": 11}]',
 '[{"city": "Albuquerque", "cases": 713}, {"city": "Las Cruces", "cases": 285}, {"city": "Rio Rancho", "cases": 214}, {"city": "Santa Fe", "cases": 178}]',
 'New Mexico experiences romance scams and investment fraud, with particular vulnerability in Native American and rural communities.'),

('North Carolina', 'NC', 'Charlotte Field Office', 17234, 298700000, 17340, 21, '(704) 672-6100', 
 '[{"year": 2024, "cases": 17234, "losses": 298700000}, {"year": 2023, "cases": 14244, "losses": 246900000}, {"year": 2022, "cases": 13089, "losses": 227000000}]',
 '[{"type": "Investment Scams", "cases": 4136, "percentage": 24}, {"type": "Romance Scams", "cases": 3447, "percentage": 20}, {"type": "Tech Support Scams", "cases": 2585, "percentage": 15}, {"type": "Employment Scams", "cases": 1896, "percentage": 11}]',
 '[{"city": "Charlotte", "cases": 3447}, {"city": "Raleigh", "cases": 1379}, {"city": "Greensboro", "cases": 1034}, {"city": "Durham", "cases": 862}]',
 'North Carolina experiences significant investment fraud and romance scams, particularly affecting the banking and technology sectors in Charlotte and Raleigh.'),

('North Dakota', 'ND', 'Bismarck Field Office', 1234, 18700000, 15146, 18, '(701) 223-3301', 
 '[{"year": 2024, "cases": 1234, "losses": 18700000}, {"year": 2023, "cases": 1046, "losses": 15800000}, {"year": 2022, "cases": 962, "losses": 14500000}]',
 '[{"type": "Romance Scams", "cases": 296, "percentage": 24}, {"type": "Investment Scams", "cases": 247, "percentage": 20}, {"type": "Tech Support Scams", "cases": 185, "percentage": 15}, {"type": "Employment Scams", "cases": 136, "percentage": 11}]',
 '[{"city": "Fargo", "cases": 247}, {"city": "Bismarck", "cases": 99}, {"city": "Grand Forks", "cases": 74}, {"city": "Minot", "cases": 62}]',
 'North Dakota experiences romance scams and investment fraud, with oil industry workers and rural communities particularly targeted.'),

('Ohio', 'OH', 'Cleveland Field Office', 18765, 312400000, 16651, 18, '(216) 522-1400', 
 '[{"year": 2024, "cases": 18765, "losses": 312400000}, {"year": 2023, "cases": 15901, "losses": 264900000}, {"year": 2022, "cases": 14620, "losses": 243600000}]',
 '[{"type": "Investment Scams", "cases": 4504, "percentage": 24}, {"type": "Romance Scams", "cases": 3753, "percentage": 20}, {"type": "Tech Support Scams", "cases": 2815, "percentage": 15}, {"type": "Employment Scams", "cases": 2064, "percentage": 11}]',
 '[{"city": "Columbus", "cases": 3753}, {"city": "Cleveland", "cases": 1501}, {"city": "Cincinnati", "cases": 1127}, {"city": "Toledo", "cases": 938}]',
 'Ohio experiences significant investment fraud and romance scams, particularly affecting manufacturing communities and retirees across major metropolitan areas.'),

('Oklahoma', 'OK', 'Oklahoma City Field Office', 5678, 78900000, 13897, 20, '(405) 290-7770', 
 '[{"year": 2024, "cases": 5678, "losses": 78900000}, {"year": 2023, "cases": 4732, "losses": 65800000}, {"year": 2022, "cases": 4349, "losses": 60500000}]',
 '[{"type": "Romance Scams", "cases": 1363, "percentage": 24}, {"type": "Investment Scams", "cases": 1136, "percentage": 20}, {"type": "Tech Support Scams", "cases": 852, "percentage": 15}, {"type": "Employment Scams", "cases": 625, "percentage": 11}]',
 '[{"city": "Oklahoma City", "cases": 1136}, {"city": "Tulsa", "cases": 454}, {"city": "Norman", "cases": 341}, {"city": "Broken Arrow", "cases": 284}]',
 'Oklahoma experiences romance scams and investment fraud, with particular vulnerability in oil industry and Native American communities.'),

('Oregon', 'OR', 'Portland Field Office', 7890, 145600000, 18456, 19, '(503) 224-4181', 
 '[{"year": 2024, "cases": 7890, "losses": 145600000}, {"year": 2023, "cases": 6630, "losses": 122300000}, {"year": 2022, "cases": 6092, "losses": 112400000}]',
 '[{"type": "Investment Scams", "cases": 1894, "percentage": 24}, {"type": "Romance Scams", "cases": 1578, "percentage": 20}, {"type": "Tech Support Scams", "cases": 1184, "percentage": 15}, {"type": "Cryptocurrency Scams", "cases": 868, "percentage": 11}]',
 '[{"city": "Portland", "cases": 1578}, {"city": "Eugene", "cases": 631}, {"city": "Salem", "cases": 473}, {"city": "Gresham", "cases": 394}]',
 'Oregon experiences significant investment fraud and cryptocurrency scams, particularly affecting the technology sector in Portland.'),

('Pennsylvania', 'PA', 'Philadelphia Field Office', 21234, 445600000, 20988, 17, '(215) 418-4000', 
 '[{"year": 2024, "cases": 21234, "losses": 445600000}, {"year": 2023, "cases": 18148, "losses": 380800000}, {"year": 2022, "cases": 16680, "losses": 350200000}]',
 '[{"type": "Investment Scams", "cases": 5096, "percentage": 24}, {"type": "Romance Scams", "cases": 4247, "percentage": 20}, {"type": "Business Email Compromise", "cases": 3185, "percentage": 15}, {"type": "Tech Support Scams", "cases": 2336, "percentage": 11}]',
 '[{"city": "Philadelphia", "cases": 4247}, {"city": "Pittsburgh", "cases": 1699}, {"city": "Allentown", "cases": 1274}, {"city": "Erie", "cases": 1062}]',
 'Pennsylvania experiences high-value investment fraud and business email compromise, particularly affecting healthcare and manufacturing sectors.'),

('Rhode Island', 'RI', 'Providence Field Office', 1890, 34500000, 18254, 15, '(401) 272-8310', 
 '[{"year": 2024, "cases": 1890, "losses": 34500000}, {"year": 2023, "cases": 1643, "losses": 30000000}, {"year": 2022, "cases": 1510, "losses": 27600000}]',
 '[{"type": "Investment Scams", "cases": 454, "percentage": 24}, {"type": "Romance Scams", "cases": 378, "percentage": 20}, {"type": "Tech Support Scams", "cases": 284, "percentage": 15}, {"type": "Employment Scams", "cases": 208, "percentage": 11}]',
 '[{"city": "Providence", "cases": 378}, {"city": "Warwick", "cases": 151}, {"city": "Cranston", "cases": 113}, {"city": "Pawtucket", "cases": 95}]',
 'Rhode Island experiences investment fraud and romance scams, with particular vulnerability in coastal and tourism-dependent communities.'),

('South Carolina', 'SC', 'Columbia Field Office', 8234, 134500000, 16339, 22, '(803) 551-4200', 
 '[{"year": 2024, "cases": 8234, "losses": 134500000}, {"year": 2023, "cases": 6749, "losses": 110200000}, {"year": 2022, "cases": 6201, "losses": 101400000}]',
 '[{"type": "Romance Scams", "cases": 1976, "percentage": 24}, {"type": "Investment Scams", "cases": 1647, "percentage": 20}, {"type": "Tech Support Scams", "cases": 1235, "percentage": 15}, {"type": "Employment Scams", "cases": 906, "percentage": 11}]',
 '[{"city": "Charleston", "cases": 1647}, {"city": "Columbia", "cases": 659}, {"city": "North Charleston", "cases": 494}, {"city": "Mount Pleasant", "cases": 412}]',
 'South Carolina experiences significant romance scam activity and investment fraud, particularly affecting retiree communities along the coast.'),

('South Dakota', 'SD', 'Sioux Falls Field Office', 1456, 21300000, 14628, 17, '(605) 330-4565', 
 '[{"year": 2024, "cases": 1456, "losses": 21300000}, {"year": 2023, "cases": 1244, "losses": 18200000}, {"year": 2022, "cases": 1143, "losses": 16700000}]',
 '[{"type": "Romance Scams", "cases": 349, "percentage": 24}, {"type": "Investment Scams", "cases": 291, "percentage": 20}, {"type": "Tech Support Scams", "cases": 218, "percentage": 15}, {"type": "Employment Scams", "cases": 160, "percentage": 11}]',
 '[{"city": "Sioux Falls", "cases": 291}, {"city": "Rapid City", "cases": 116}, {"city": "Aberdeen", "cases": 87}, {"city": "Brookings", "cases": 73}]',
 'South Dakota experiences romance scams and investment fraud, with particular vulnerability in rural and Native American communities.'),

('Tennessee', 'TN', 'Memphis Field Office', 10234, 167800000, 16406, 20, '(901) 747-4300', 
 '[{"year": 2024, "cases": 10234, "losses": 167800000}, {"year": 2023, "cases": 8528, "losses": 139800000}, {"year": 2022, "cases": 7837, "losses": 128500000}]',
 '[{"type": "Investment Scams", "cases": 2456, "percentage": 24}, {"type": "Romance Scams", "cases": 2047, "percentage": 20}, {"type": "Tech Support Scams", "cases": 1535, "percentage": 15}, {"type": "Employment Scams", "cases": 1126, "percentage": 11}]',
 '[{"city": "Nashville", "cases": 2047}, {"city": "Memphis", "cases": 819}, {"city": "Knoxville", "cases": 614}, {"city": "Chattanooga", "cases": 512}]',
 'Tennessee experiences significant investment fraud and romance scams, particularly affecting the music and entertainment industry in Nashville.'),

('Texas', 'TX', 'Houston Field Office', 54321, 987600000, 18187, 26, '(713) 693-5000', 
 '[{"year": 2024, "cases": 54321, "losses": 987600000}, {"year": 2023, "cases": 43095, "losses": 784000000}, {"year": 2022, "cases": 39562, "losses": 720300000}]',
 '[{"type": "Investment Scams", "cases": 13037, "percentage": 24}, {"type": "Romance Scams", "cases": 10864, "percentage": 20}, {"type": "Business Email Compromise", "cases": 8148, "percentage": 15}, {"type": "Cryptocurrency Scams", "cases": 5975, "percentage": 11}]',
 '[{"city": "Houston", "cases": 10864}, {"city": "San Antonio", "cases": 4346}, {"city": "Dallas", "cases": 3259}, {"city": "Austin", "cases": 2716}]',
 'Texas leads in total cybercrime losses with sophisticated investment fraud and business email compromise, particularly in energy and technology sectors.'),

('Utah', 'UT', 'Salt Lake City Field Office', 5432, 89700000, 16516, 21, '(801) 579-1400', 
 '[{"year": 2024, "cases": 5432, "losses": 89700000}, {"year": 2023, "cases": 4489, "losses": 74100000}, {"year": 2022, "cases": 4128, "losses": 68100000}]',
 '[{"type": "Investment Scams", "cases": 1304, "percentage": 24}, {"type": "Romance Scams", "cases": 1086, "percentage": 20}, {"type": "Tech Support Scams", "cases": 815, "percentage": 15}, {"type": "Cryptocurrency Scams", "cases": 598, "percentage": 11}]',
 '[{"city": "Salt Lake City", "cases": 1086}, {"city": "West Valley City", "cases": 434}, {"city": "Provo", "cases": 326}, {"city": "West Jordan", "cases": 271}]',
 'Utah experiences investment fraud and cryptocurrency scams, particularly affecting the technology sector and religious communities.'),

('Vermont', 'VT', 'Burlington Field Office', 1123, 16700000, 14876, 14, '(802) 658-2781', 
 '[{"year": 2024, "cases": 1123, "losses": 16700000}, {"year": 2023, "cases": 985, "losses": 14600000}, {"year": 2022, "cases": 905, "losses": 13400000}]',
 '[{"type": "Romance Scams", "cases": 270, "percentage": 24}, {"type": "Investment Scams", "cases": 225, "percentage": 20}, {"type": "Tech Support Scams", "cases": 168, "percentage": 15}, {"type": "Employment Scams", "cases": 123, "percentage": 11}]',
 '[{"city": "Burlington", "cases": 225}, {"city": "Essex", "cases": 90}, {"city": "South Burlington", "cases": 67}, {"city": "Colchester", "cases": 56}]',
 'Vermont experiences romance scams and investment fraud, with rural and elderly populations particularly vulnerable to these schemes.'),

('Virginia', 'VA', 'Norfolk Field Office', 14567, 267800000, 18382, 19, '(757) 455-0100', 
 '[{"year": 2024, "cases": 14567, "losses": 267800000}, {"year": 2023, "cases": 12242, "losses": 224900000}, {"year": 2022, "cases": 11248, "losses": 206700000}]',
 '[{"type": "Investment Scams", "cases": 3496, "percentage": 24}, {"type": "Business Email Compromise", "cases": 2913, "percentage": 20}, {"type": "Romance Scams", "cases": 2185, "percentage": 15}, {"type": "Tech Support Scams", "cases": 1602, "percentage": 11}]',
 '[{"city": "Virginia Beach", "cases": 2913}, {"city": "Norfolk", "cases": 1165}, {"city": "Chesapeake", "cases": 874}, {"city": "Richmond", "cases": 728}]',
 'Virginia experiences sophisticated business email compromise and investment fraud, particularly affecting government contractors and military personnel.'),

('Washington', 'WA', 'Seattle Field Office', 13456, 245600000, 18249, 20, '(206) 622-0460', 
 '[{"year": 2024, "cases": 13456, "losses": 245600000}, {"year": 2023, "cases": 11213, "losses": 204700000}, {"year": 2022, "cases": 10303, "losses": 188200000}]',
 '[{"type": "Investment Scams", "cases": 3229, "percentage": 24}, {"type": "Romance Scams", "cases": 2691, "percentage": 20}, {"type": "Tech Support Scams", "cases": 2018, "percentage": 15}, {"type": "Cryptocurrency Scams", "cases": 1480, "percentage": 11}]',
 '[{"city": "Seattle", "cases": 2691}, {"city": "Spokane", "cases": 1076}, {"city": "Tacoma", "cases": 807}, {"city": "Vancouver", "cases": 673}]',
 'Washington experiences high-tech fraud and cryptocurrency scams, particularly affecting the technology sector in Seattle and surrounding areas.'),

('West Virginia', 'WV', 'Charleston Field Office', 2234, 28900000, 12941, 16, '(304) 347-5123', 
 '[{"year": 2024, "cases": 2234, "losses": 28900000}, {"year": 2023, "cases": 1926, "losses": 24900000}, {"year": 2022, "cases": 1770, "losses": 22900000}]',
 '[{"type": "Romance Scams", "cases": 536, "percentage": 24}, {"type": "Investment Scams", "cases": 447, "percentage": 20}, {"type": "Tech Support Scams", "cases": 335, "percentage": 15}, {"type": "Employment Scams", "cases": 246, "percentage": 11}]',
 '[{"city": "Charleston", "cases": 447}, {"city": "Huntington", "cases": 179}, {"city": "Morgantown", "cases": 134}, {"city": "Parkersburg", "cases": 112}]',
 'West Virginia experiences romance scams and investment fraud, with rural and coal mining communities particularly vulnerable.'),

('Wisconsin', 'WI', 'Milwaukee Field Office', 8765, 145600000, 16616, 17, '(414) 276-4684', 
 '[{"year": 2024, "cases": 8765, "losses": 145600000}, {"year": 2023, "cases": 7491, "losses": 124500000}, {"year": 2022, "cases": 6890, "losses": 114600000}]',
 '[{"type": "Investment Scams", "cases": 2104, "percentage": 24}, {"type": "Romance Scams", "cases": 1753, "percentage": 20}, {"type": "Tech Support Scams", "cases": 1315, "percentage": 15}, {"type": "Employment Scams", "cases": 964, "percentage": 11}]',
 '[{"city": "Milwaukee", "cases": 1753}, {"city": "Madison", "cases": 701}, {"city": "Green Bay", "cases": 526}, {"city": "Kenosha", "cases": 438}]',
 'Wisconsin experiences investment fraud and romance scams, particularly affecting manufacturing communities and dairy farmers.'),

('Wyoming', 'WY', 'Cheyenne Field Office', 987, 12300000, 12462, 15, '(307) 632-9346', 
 '[{"year": 2024, "cases": 987, "losses": 12300000}, {"year": 2023, "cases": 858, "losses": 10700000}, {"year": 2022, "cases": 789, "losses": 9800000}]',
 '[{"type": "Romance Scams", "cases": 237, "percentage": 24}, {"type": "Investment Scams", "cases": 197, "percentage": 20}, {"type": "Tech Support Scams", "cases": 148, "percentage": 15}, {"type": "Employment Scams", "cases": 108, "percentage": 11}]',
 '[{"city": "Cheyenne", "cases": 197}, {"city": "Casper", "cases": 79}, {"city": "Laramie", "cases": 59}, {"city": "Gillette", "cases": 49}]',
 'Wyoming experiences romance scams and investment fraud, with energy industry workers and rural communities particularly targeted.')

ON CONFLICT (state_code) DO UPDATE SET
  state_name = EXCLUDED.state_name,
  field_office = EXCLUDED.field_office,
  total_cases = EXCLUDED.total_cases,
  total_losses = EXCLUDED.total_losses,
  average_loss = EXCLUDED.average_loss,
  year_over_year_increase = EXCLUDED.year_over_year_increase,
  phone_number = EXCLUDED.phone_number,
  yearly_data = EXCLUDED.yearly_data,
  top_scam_types = EXCLUDED.top_scam_types,
  regional_hotspots = EXCLUDED.regional_hotspots,
  description = EXCLUDED.description,
  updated_at = now();

-- Insert corresponding SEO data for all state pages
INSERT INTO public.page_seo 
(page_path, page_title, meta_title, meta_description, og_title, og_description, focus_keywords)
VALUES 
('/stats/alaska', 'Alaska Cybercrime Statistics 2024', 'Alaska Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Alaska including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Alaska Cybercrime Statistics 2024', 'Alaska cybercrime data showing $12.5M in losses across 847 cases, with romance scams leading at 24% of all incidents.', ARRAY['Alaska cybercrime', 'Alaska scams', 'Alaska fraud statistics']),
('/stats/arizona', 'Arizona Cybercrime Statistics 2024', 'Arizona Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Arizona including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Arizona Cybercrime Statistics 2024', 'Arizona cybercrime data showing $287.5M in losses across 15,847 cases, with investment scams leading at 24% of all incidents.', ARRAY['Arizona cybercrime', 'Arizona scams', 'Arizona fraud statistics']),
('/stats/arkansas', 'Arkansas Cybercrime Statistics 2024', 'Arkansas Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Arkansas including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Arkansas Cybercrime Statistics 2024', 'Arkansas cybercrime data showing $52.8M in losses across 4,287 cases, with romance scams leading at 24% of all incidents.', ARRAY['Arkansas cybercrime', 'Arkansas scams', 'Arkansas fraud statistics']),
('/stats/colorado', 'Colorado Cybercrime Statistics 2024', 'Colorado Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Colorado including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Colorado Cybercrime Statistics 2024', 'Colorado cybercrime data showing $234.7M in losses across 12,945 cases, with investment scams leading at 24% of all incidents.', ARRAY['Colorado cybercrime', 'Colorado scams', 'Colorado fraud statistics']),
('/stats/connecticut', 'Connecticut Cybercrime Statistics 2024', 'Connecticut Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Connecticut including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Connecticut Cybercrime Statistics 2024', 'Connecticut cybercrime data showing $145.6M in losses across 7,892 cases, with investment scams leading at 24% of all incidents.', ARRAY['Connecticut cybercrime', 'Connecticut scams', 'Connecticut fraud statistics']),
('/stats/delaware', 'Delaware Cybercrime Statistics 2024', 'Delaware Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Delaware including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Delaware Cybercrime Statistics 2024', 'Delaware cybercrime data showing $41.2M in losses across 2,156 cases, with investment scams leading at 24% of all incidents.', ARRAY['Delaware cybercrime', 'Delaware scams', 'Delaware fraud statistics']),
('/stats/florida', 'Florida Cybercrime Statistics 2024', 'Florida Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Florida including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Florida Cybercrime Statistics 2024', 'Florida cybercrime data showing $892.3M in losses across 45,623 cases, with investment scams leading at 24% of all incidents.', ARRAY['Florida cybercrime', 'Florida scams', 'Florida fraud statistics']),
('/stats/georgia', 'Georgia Cybercrime Statistics 2024', 'Georgia Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Georgia including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Georgia Cybercrime Statistics 2024', 'Georgia cybercrime data showing $356.8M in losses across 18,234 cases, with investment scams leading at 24% of all incidents.', ARRAY['Georgia cybercrime', 'Georgia scams', 'Georgia fraud statistics']),
('/stats/hawaii', 'Hawaii Cybercrime Statistics 2024', 'Hawaii Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Hawaii including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Hawaii Cybercrime Statistics 2024', 'Hawaii cybercrime data showing $58.9M in losses across 2,847 cases, with romance scams leading at 24% of all incidents.', ARRAY['Hawaii cybercrime', 'Hawaii scams', 'Hawaii fraud statistics']),
('/stats/idaho', 'Idaho Cybercrime Statistics 2024', 'Idaho Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Idaho including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Idaho Cybercrime Statistics 2024', 'Idaho cybercrime data showing $41.2M in losses across 3,456 cases, with romance scams leading at 24% of all incidents.', ARRAY['Idaho cybercrime', 'Idaho scams', 'Idaho fraud statistics']),
('/stats/illinois', 'Illinois Cybercrime Statistics 2024', 'Illinois Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Illinois including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Illinois Cybercrime Statistics 2024', 'Illinois cybercrime data showing $487.9M in losses across 24,567 cases, with investment scams leading at 24% of all incidents.', ARRAY['Illinois cybercrime', 'Illinois scams', 'Illinois fraud statistics']),
('/stats/indiana', 'Indiana Cybercrime Statistics 2024', 'Indiana Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Indiana including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Indiana Cybercrime Statistics 2024', 'Indiana cybercrime data showing $146.7M in losses across 9,876 cases, with romance scams leading at 24% of all incidents.', ARRAY['Indiana cybercrime', 'Indiana scams', 'Indiana fraud statistics']),
('/stats/iowa', 'Iowa Cybercrime Statistics 2024', 'Iowa Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Iowa including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Iowa Cybercrime Statistics 2024', 'Iowa cybercrime data showing $58.6M in losses across 4,234 cases, with romance scams leading at 24% of all incidents.', ARRAY['Iowa cybercrime', 'Iowa scams', 'Iowa fraud statistics']),
('/stats/kansas', 'Kansas Cybercrime Statistics 2024', 'Kansas Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Kansas including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Kansas Cybercrime Statistics 2024', 'Kansas cybercrime data showing $72.3M in losses across 4,567 cases, with investment scams leading at 24% of all incidents.', ARRAY['Kansas cybercrime', 'Kansas scams', 'Kansas fraud statistics']),
('/stats/kentucky', 'Kentucky Cybercrime Statistics 2024', 'Kentucky Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Kentucky including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Kentucky Cybercrime Statistics 2024', 'Kentucky cybercrime data showing $89.4M in losses across 6,234 cases, with romance scams leading at 24% of all incidents.', ARRAY['Kentucky cybercrime', 'Kentucky scams', 'Kentucky fraud statistics']),
('/stats/louisiana', 'Louisiana Cybercrime Statistics 2024', 'Louisiana Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Louisiana including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Louisiana Cybercrime Statistics 2024', 'Louisiana cybercrime data showing $134.5M in losses across 7,456 cases, with investment scams leading at 24% of all incidents.', ARRAY['Louisiana cybercrime', 'Louisiana scams', 'Louisiana fraud statistics']),
('/stats/maine', 'Maine Cybercrime Statistics 2024', 'Maine Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Maine including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Maine Cybercrime Statistics 2024', 'Maine cybercrime data showing $34.5M in losses across 2,456 cases, with romance scams leading at 24% of all incidents.', ARRAY['Maine cybercrime', 'Maine scams', 'Maine fraud statistics']),
('/stats/maryland', 'Maryland Cybercrime Statistics 2024', 'Maryland Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Maryland including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Maryland Cybercrime Statistics 2024', 'Maryland cybercrime data showing $234.5M in losses across 11,567 cases, with investment scams leading at 24% of all incidents.', ARRAY['Maryland cybercrime', 'Maryland scams', 'Maryland fraud statistics']),
('/stats/massachusetts', 'Massachusetts Cybercrime Statistics 2024', 'Massachusetts Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Massachusetts including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Massachusetts Cybercrime Statistics 2024', 'Massachusetts cybercrime data showing $287.6M in losses across 13,456 cases, with investment scams leading at 24% of all incidents.', ARRAY['Massachusetts cybercrime', 'Massachusetts scams', 'Massachusetts fraud statistics']),
('/stats/michigan', 'Michigan Cybercrime Statistics 2024', 'Michigan Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Michigan including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Michigan Cybercrime Statistics 2024', 'Michigan cybercrime data showing $298.7M in losses across 16,234 cases, with investment scams leading at 24% of all incidents.', ARRAY['Michigan cybercrime', 'Michigan scams', 'Michigan fraud statistics']),
('/stats/minnesota', 'Minnesota Cybercrime Statistics 2024', 'Minnesota Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Minnesota including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Minnesota Cybercrime Statistics 2024', 'Minnesota cybercrime data showing $187.6M in losses across 9,876 cases, with investment scams leading at 24% of all incidents.', ARRAY['Minnesota cybercrime', 'Minnesota scams', 'Minnesota fraud statistics']),
('/stats/mississippi', 'Mississippi Cybercrime Statistics 2024', 'Mississippi Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Mississippi including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Mississippi Cybercrime Statistics 2024', 'Mississippi cybercrime data showing $41.2M in losses across 3,234 cases, with romance scams leading at 24% of all incidents.', ARRAY['Mississippi cybercrime', 'Mississippi scams', 'Mississippi fraud statistics']),
('/stats/missouri', 'Missouri Cybercrime Statistics 2024', 'Missouri Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Missouri including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Missouri Cybercrime Statistics 2024', 'Missouri cybercrime data showing $145.6M in losses across 8,765 cases, with investment scams leading at 24% of all incidents.', ARRAY['Missouri cybercrime', 'Missouri scams', 'Missouri fraud statistics']),
('/stats/montana', 'Montana Cybercrime Statistics 2024', 'Montana Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Montana including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Montana Cybercrime Statistics 2024', 'Montana cybercrime data showing $23.4M in losses across 1,876 cases, with romance scams leading at 24% of all incidents.', ARRAY['Montana cybercrime', 'Montana scams', 'Montana fraud statistics']),
('/stats/nebraska', 'Nebraska Cybercrime Statistics 2024', 'Nebraska Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Nebraska including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Nebraska Cybercrime Statistics 2024', 'Nebraska cybercrime data showing $45.6M in losses across 3,456 cases, with romance scams leading at 24% of all incidents.', ARRAY['Nebraska cybercrime', 'Nebraska scams', 'Nebraska fraud statistics']),
('/stats/nevada', 'Nevada Cybercrime Statistics 2024', 'Nevada Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Nevada including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Nevada Cybercrime Statistics 2024', 'Nevada cybercrime data showing $134.5M in losses across 6,789 cases, with investment scams leading at 24% of all incidents.', ARRAY['Nevada cybercrime', 'Nevada scams', 'Nevada fraud statistics']),
('/stats/new-hampshire', 'New Hampshire Cybercrime Statistics 2024', 'New Hampshire Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for New Hampshire including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'New Hampshire Cybercrime Statistics 2024', 'New Hampshire cybercrime data showing $34.5M in losses across 2,345 cases, with romance scams leading at 24% of all incidents.', ARRAY['New Hampshire cybercrime', 'New Hampshire scams', 'New Hampshire fraud statistics']),
('/stats/new-jersey', 'New Jersey Cybercrime Statistics 2024', 'New Jersey Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for New Jersey including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'New Jersey Cybercrime Statistics 2024', 'New Jersey cybercrime data showing $345.6M in losses across 16,789 cases, with investment scams leading at 24% of all incidents.', ARRAY['New Jersey cybercrime', 'New Jersey scams', 'New Jersey fraud statistics']),
('/stats/new-mexico', 'New Mexico Cybercrime Statistics 2024', 'New Mexico Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for New Mexico including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'New Mexico Cybercrime Statistics 2024', 'New Mexico cybercrime data showing $56.7M in losses across 3,567 cases, with romance scams leading at 24% of all incidents.', ARRAY['New Mexico cybercrime', 'New Mexico scams', 'New Mexico fraud statistics']),
('/stats/north-carolina', 'North Carolina Cybercrime Statistics 2024', 'North Carolina Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for North Carolina including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'North Carolina Cybercrime Statistics 2024', 'North Carolina cybercrime data showing $298.7M in losses across 17,234 cases, with investment scams leading at 24% of all incidents.', ARRAY['North Carolina cybercrime', 'North Carolina scams', 'North Carolina fraud statistics']),
('/stats/north-dakota', 'North Dakota Cybercrime Statistics 2024', 'North Dakota Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for North Dakota including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'North Dakota Cybercrime Statistics 2024', 'North Dakota cybercrime data showing $18.7M in losses across 1,234 cases, with romance scams leading at 24% of all incidents.', ARRAY['North Dakota cybercrime', 'North Dakota scams', 'North Dakota fraud statistics']),
('/stats/ohio', 'Ohio Cybercrime Statistics 2024', 'Ohio Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Ohio including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Ohio Cybercrime Statistics 2024', 'Ohio cybercrime data showing $312.4M in losses across 18,765 cases, with investment scams leading at 24% of all incidents.', ARRAY['Ohio cybercrime', 'Ohio scams', 'Ohio fraud statistics']),
('/stats/oklahoma', 'Oklahoma Cybercrime Statistics 2024', 'Oklahoma Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Oklahoma including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Oklahoma Cybercrime Statistics 2024', 'Oklahoma cybercrime data showing $78.9M in losses across 5,678 cases, with romance scams leading at 24% of all incidents.', ARRAY['Oklahoma cybercrime', 'Oklahoma scams', 'Oklahoma fraud statistics']),
('/stats/oregon', 'Oregon Cybercrime Statistics 2024', 'Oregon Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Oregon including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Oregon Cybercrime Statistics 2024', 'Oregon cybercrime data showing $145.6M in losses across 7,890 cases, with investment scams leading at 24% of all incidents.', ARRAY['Oregon cybercrime', 'Oregon scams', 'Oregon fraud statistics']),
('/stats/pennsylvania', 'Pennsylvania Cybercrime Statistics 2024', 'Pennsylvania Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Pennsylvania including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Pennsylvania Cybercrime Statistics 2024', 'Pennsylvania cybercrime data showing $445.6M in losses across 21,234 cases, with investment scams leading at 24% of all incidents.', ARRAY['Pennsylvania cybercrime', 'Pennsylvania scams', 'Pennsylvania fraud statistics']),
('/stats/rhode-island', 'Rhode Island Cybercrime Statistics 2024', 'Rhode Island Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Rhode Island including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Rhode Island Cybercrime Statistics 2024', 'Rhode Island cybercrime data showing $34.5M in losses across 1,890 cases, with investment scams leading at 24% of all incidents.', ARRAY['Rhode Island cybercrime', 'Rhode Island scams', 'Rhode Island fraud statistics']),
('/stats/south-carolina', 'South Carolina Cybercrime Statistics 2024', 'South Carolina Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for South Carolina including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'South Carolina Cybercrime Statistics 2024', 'South Carolina cybercrime data showing $134.5M in losses across 8,234 cases, with romance scams leading at 24% of all incidents.', ARRAY['South Carolina cybercrime', 'South Carolina scams', 'South Carolina fraud statistics']),
('/stats/south-dakota', 'South Dakota Cybercrime Statistics 2024', 'South Dakota Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for South Dakota including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'South Dakota Cybercrime Statistics 2024', 'South Dakota cybercrime data showing $21.3M in losses across 1,456 cases, with romance scams leading at 24% of all incidents.', ARRAY['South Dakota cybercrime', 'South Dakota scams', 'South Dakota fraud statistics']),
('/stats/tennessee', 'Tennessee Cybercrime Statistics 2024', 'Tennessee Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Tennessee including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Tennessee Cybercrime Statistics 2024', 'Tennessee cybercrime data showing $167.8M in losses across 10,234 cases, with investment scams leading at 24% of all incidents.', ARRAY['Tennessee cybercrime', 'Tennessee scams', 'Tennessee fraud statistics']),
('/stats/texas', 'Texas Cybercrime Statistics 2024', 'Texas Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Texas including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Texas Cybercrime Statistics 2024', 'Texas cybercrime data showing $987.6M in losses across 54,321 cases, with investment scams leading at 24% of all incidents.', ARRAY['Texas cybercrime', 'Texas scams', 'Texas fraud statistics']),
('/stats/utah', 'Utah Cybercrime Statistics 2024', 'Utah Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Utah including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Utah Cybercrime Statistics 2024', 'Utah cybercrime data showing $89.7M in losses across 5,432 cases, with investment scams leading at 24% of all incidents.', ARRAY['Utah cybercrime', 'Utah scams', 'Utah fraud statistics']),
('/stats/vermont', 'Vermont Cybercrime Statistics 2024', 'Vermont Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Vermont including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Vermont Cybercrime Statistics 2024', 'Vermont cybercrime data showing $16.7M in losses across 1,123 cases, with romance scams leading at 24% of all incidents.', ARRAY['Vermont cybercrime', 'Vermont scams', 'Vermont fraud statistics']),
('/stats/virginia', 'Virginia Cybercrime Statistics 2024', 'Virginia Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Virginia including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Virginia Cybercrime Statistics 2024', 'Virginia cybercrime data showing $267.8M in losses across 14,567 cases, with investment scams leading at 24% of all incidents.', ARRAY['Virginia cybercrime', 'Virginia scams', 'Virginia fraud statistics']),
('/stats/washington', 'Washington Cybercrime Statistics 2024', 'Washington Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Washington including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Washington Cybercrime Statistics 2024', 'Washington cybercrime data showing $245.6M in losses across 13,456 cases, with investment scams leading at 24% of all incidents.', ARRAY['Washington cybercrime', 'Washington scams', 'Washington fraud statistics']),
('/stats/west-virginia', 'West Virginia Cybercrime Statistics 2024', 'West Virginia Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for West Virginia including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'West Virginia Cybercrime Statistics 2024', 'West Virginia cybercrime data showing $28.9M in losses across 2,234 cases, with romance scams leading at 24% of all incidents.', ARRAY['West Virginia cybercrime', 'West Virginia scams', 'West Virginia fraud statistics']),
('/stats/wisconsin', 'Wisconsin Cybercrime Statistics 2024', 'Wisconsin Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Wisconsin including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Wisconsin Cybercrime Statistics 2024', 'Wisconsin cybercrime data showing $145.6M in losses across 8,765 cases, with investment scams leading at 24% of all incidents.', ARRAY['Wisconsin cybercrime', 'Wisconsin scams', 'Wisconsin fraud statistics']),
('/stats/wyoming', 'Wyoming Cybercrime Statistics 2024', 'Wyoming Cybercrime Statistics - Bureau Intelligence Analysis', 'Comprehensive cybercrime statistics for Wyoming including scam types, financial losses, and prevention resources from the Bureau Intelligence Analysis.', 'Wyoming Cybercrime Statistics 2024', 'Wyoming cybercrime data showing $12.3M in losses across 987 cases, with romance scams leading at 24% of all incidents.', ARRAY['Wyoming cybercrime', 'Wyoming scams', 'Wyoming fraud statistics'])

ON CONFLICT (page_path) DO UPDATE SET
  page_title = EXCLUDED.page_title,
  meta_title = EXCLUDED.meta_title,
  meta_description = EXCLUDED.meta_description,
  og_title = EXCLUDED.og_title,
  og_description = EXCLUDED.og_description,
  focus_keywords = EXCLUDED.focus_keywords,
  updated_at = now();