// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdbsnzzgrowztbtgxsag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkYnNuenpncm93enRidGd4c2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzOTI2NTQsImV4cCI6MjA2Nzk2ODY1NH0.8RN0sO79t0BlZVf67JP3MEq8WpRZ_hOZoqFGCZMwGL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});